/* ===================== DUMMY DATA ===================== */

const CATEGORIES = [
  { id: "kada", name: "Mahakal Kada", icon: "fa-om", tint: "from-orange-500 to-red-600" },
  { id: "ratna", name: "Ratna Bracelets", icon: "fa-gem", tint: "from-amber-400 to-orange-500" },
  { id: "rudraksha", name: "Rudraksha", icon: "fa-spa", tint: "from-yellow-600 to-orange-700" },
  { id: "girls", name: "Girls Accessories", icon: "fa-star-of-life", tint: "from-pink-400 to-orange-400" },
  { id: "gifts", name: "Gift Items", icon: "fa-gift", tint: "from-red-500 to-amber-500" },
  { id: "healing", name: "Healing Bracelets", icon: "fa-hand-holding-medical", tint: "from-emerald-500 to-teal-600" },
  { id: "nazar", name: "Nazar Protection", icon: "fa-eye", tint: "from-slate-700 to-indigo-700" },
  { id: "spiritual", name: "Spiritual Products", icon: "fa-om", tint: "from-orange-600 to-amber-700" },
];

const PRODUCTS = [
  { id: 1, name: "Mahakal Trishul Kada", cat: "kada", price: 1299, mrp: 2199, rating: 4.8, reviews: 342, emoji: "🔱", badge: "Bestseller",
    desc: "Handcrafted pure copper Mahakal Trishul Kada, blessed at Ujjain Mahakaleshwar temple.",
    stone: "Copper & Rudraksha bead", zodiac: "All Signs", planet: "Shani (Saturn)", chakra: "Root Chakra",
    wearing: "Wear on right wrist, preferably on a Monday morning after cleansing.",
    care: "Avoid water & soap contact. Store in a dry cloth pouch." },
  { id: 2, name: "Ratna Navratna Bracelet", cat: "ratna", price: 1899, mrp: 2999, rating: 4.7, reviews: 218, emoji: "💎", badge: "Premium",
    desc: "Nine sacred gemstones combined to balance all planetary energies.",
    stone: "Navratna (9 gems)", zodiac: "All Signs", planet: "All Nine Planets", chakra: "All Chakras",
    wearing: "Wear on the hand as per your dominant hand, on an auspicious day.",
    care: "Keep away from perfumes and chemicals." },
  { id: 3, name: "5 Mukhi Rudraksha Mala", cat: "rudraksha", price: 899, mrp: 1499, rating: 4.9, reviews: 512, emoji: "🪷", badge: "Original",
    desc: "Certified original Nepali 5 Mukhi Rudraksha, strung on pure silk thread.",
    stone: "5 Mukhi Rudraksha", zodiac: "All Signs", planet: "Guru (Jupiter)", chakra: "Heart Chakra",
    wearing: "Wear around the neck, close to the heart chakra.",
    care: "Oil lightly once a month. Avoid direct sunlight for long hours." },
  { id: 4, name: "Rose Quartz Love Bracelet", cat: "girls", price: 599, mrp: 999, rating: 4.6, reviews: 156, emoji: "🌸", badge: "Trending",
    desc: "Elegant rose quartz bracelet for love, compassion and inner peace.",
    stone: "Rose Quartz", zodiac: "Taurus, Libra", planet: "Shukra (Venus)", chakra: "Heart Chakra",
    wearing: "Wear on the left wrist to attract love energy.",
    care: "Cleanse under moonlight once a week." },
  { id: 5, name: "Mahakal Blessing Gift Box", cat: "gifts", price: 1499, mrp: 2499, rating: 4.8, reviews: 98, emoji: "🎁", badge: "Limited",
    desc: "Curated gift box with kada, rudraksha mala and sacred bhasma.",
    stone: "Mixed", zodiac: "All Signs", planet: "—", chakra: "—",
    wearing: "Ideal as a gift for festivals & pooja.",
    care: "Store items separately in provided pouches." },
  { id: 6, name: "7 Chakra Healing Bracelet", cat: "healing", price: 449, mrp: 799, rating: 4.7, reviews: 289, emoji: "🧿", badge: "Bestseller",
    desc: "Seven natural stones aligned to balance all seven chakras.",
    stone: "7 Chakra Stones", zodiac: "All Signs", planet: "All", chakra: "All 7 Chakras",
    wearing: "Wear on either wrist during meditation and daily.",
    care: "Recharge under sunlight for 10 minutes weekly." },
  { id: 7, name: "Black Onyx Nazar Suraksha Kada", cat: "nazar", price: 699, mrp: 1199, rating: 4.9, reviews: 401, emoji: "🖤", badge: "Popular",
    desc: "Protective black onyx kada that shields against evil eye and negative energy.",
    stone: "Black Onyx", zodiac: "Scorpio", planet: "Shani (Saturn)", chakra: "Root Chakra",
    wearing: "Wear on the right hand for maximum protection.",
    care: "Avoid contact with harsh chemicals." },
  { id: 8, name: "Om Namah Shivaya Pendant", cat: "spiritual", price: 799, mrp: 1299, rating: 4.8, reviews: 176, emoji: "🕉️", badge: "Sacred",
    desc: "Pure brass Om pendant engraved with the Panchakshari mantra.",
    stone: "Brass", zodiac: "All Signs", planet: "Shiva Graha", chakra: "Crown Chakra",
    wearing: "Wear close to chest on a black or red thread.",
    care: "Polish gently with a soft dry cloth." },
  { id: 9, name: "Tiger Eye Confidence Bracelet", cat: "healing", price: 549, mrp: 899, rating: 4.6, reviews: 134, emoji: "🐯", badge: "New",
    desc: "Tiger eye stone bracelet known to boost confidence and willpower.",
    stone: "Tiger Eye", zodiac: "Leo, Capricorn", planet: "Surya (Sun)", chakra: "Solar Plexus",
    wearing: "Wear on the right wrist while at work or study.",
    care: "Avoid water. Clean with dry cloth only." },
  { id: 10, name: "Panchmukhi Rudraksha Kada", cat: "rudraksha", price: 999, mrp: 1699, rating: 4.7, reviews: 210, emoji: "🔱", badge: "Bestseller",
    desc: "Five-faced Rudraksha beads set in an adjustable copper kada.",
    stone: "Panchmukhi Rudraksha", zodiac: "All Signs", planet: "Guru (Jupiter)", chakra: "Heart Chakra",
    wearing: "Wear on right wrist after Monday morning cleansing.",
    care: "Keep dry, oil once monthly." },
];

const ZODIAC_DATA = {
  Aries: { stone: "Red Coral", color: "Red", planet: "Mars (Mangal)", benefit: "Boosts courage, leadership & vitality." },
  Taurus: { stone: "Diamond / White Sapphire", color: "White", planet: "Venus (Shukra)", benefit: "Enhances love, luxury & stability." },
  Gemini: { stone: "Emerald", color: "Green", planet: "Mercury (Budh)", benefit: "Sharpens intellect & communication." },
  Cancer: { stone: "Pearl", color: "White", planet: "Moon (Chandra)", benefit: "Calms emotions & brings peace of mind." },
  Leo: { stone: "Ruby", color: "Red", planet: "Sun (Surya)", benefit: "Boosts confidence & leadership energy." },
  Virgo: { stone: "Emerald", color: "Green", planet: "Mercury (Budh)", benefit: "Improves focus & analytical clarity." },
  Libra: { stone: "Diamond", color: "White/Pink", planet: "Venus (Shukra)", benefit: "Balances relationships & harmony." },
  Scorpio: { stone: "Red Coral", color: "Red", planet: "Mars (Mangal)", benefit: "Strengthens willpower & protection." },
  Sagittarius: { stone: "Yellow Sapphire", color: "Yellow", planet: "Jupiter (Guru)", benefit: "Attracts wisdom & prosperity." },
  Capricorn: { stone: "Blue Sapphire", color: "Blue", planet: "Saturn (Shani)", benefit: "Brings discipline & career growth." },
  Aquarius: { stone: "Blue Sapphire", color: "Blue", planet: "Saturn (Shani)", benefit: "Enhances innovation & independence." },
  Pisces: { stone: "Yellow Sapphire", color: "Yellow", planet: "Jupiter (Guru)", benefit: "Deepens intuition & spirituality." },
};

const REVIEWS = [
  { name: "Priya Sharma", rating: 5, text: "Beautiful quality and fast delivery. The kada feels authentic and blessed.", loc: "Ujjain" },
  { name: "Rohit Verma", rating: 5, text: "Bought the rudraksha mala for my father. He loves it, very original product.", loc: "Indore" },
  { name: "Ananya Singh", rating: 4, text: "Loved the packaging and the gift box. Perfect for Diwali gifting.", loc: "Bhopal" },
  { name: "Karan Mehta", rating: 5, text: "The lucky stone recommendation was spot on. Great experience overall.", loc: "Delhi" },
];

const money = (n) => "₹" + n.toLocaleString("en-IN");
const discountOf = (price, mrp) => Math.round(((mrp - price) / mrp) * 100);
const findProduct = (id) => PRODUCTS.find((p) => p.id === Number(id));